### ISSUE TITLE
Two cards removed

### ISSUE THREAD

**Issue by Peremptor** [TobiasBielefeld/Simple-Solitaire#58]
When for example in Pyramid, say two 4 lie next to each other and you move a 9 to them, and if your aiming is bad so you touch both 4, both of them will vanish. 
I don't know much about the other games, just playing the ones I know 😀, but I think it would be in any game where you have to move one card to another. 
Although I don't have any experience with Android programming, I think you will have to calculate how much of one card lies on the other one and just remove the card with the higher part. 

You may answer in English or German ☺️

**Comment by TobiasBielefeld** [comment]
I'll answer in English, so other people can read this too :)

Thanks for noticing this error! It will be fixed in the next app update.
This only affects Pyramid, because its movement method is a bit special. Every other game already takes the card with the highest intersection, but I need to adjust it a bit for Pyramid :D

**Comment by TobiasBielefeld** [comment]
Okay, this is fixed in version 3.8
