### ISSUE TITLE
Spider end-of-game issue

### ISSUE THREAD

**Issue by logic** [TobiasBielefeld/Simple-Solitaire#7]
As of a couple of releases ago, I've noticed that Spider will often not end the game when the last tableau stack is merged and moved to the foundation stacks, and you're left with an empty tableau and no way to end the game.

Hitting undo and redoing the last move a few times (or splitting the last merge into a couple of additional moves) seems to eventually cause the game to end properly, which makes me think it's something timing-related?

I mostly play Spider and Klondike; I don't see this behavior with Klondike, but I usually auto-complete Klondike (which isn't an option with Spider), so perhaps it's related?

FWIW, I'm using the F-Droid build, on a Nexus 5 running android 7.1.1 (cyanogenmod).

**Comment by TobiasBielefeld** [comment]
Hi! Thanks for the issue report.

The problem was: I changed the way of moving the cards to the foundation stacks and forgot to add the win test... It's also tested at another point, so it still worked sometimes.

So i added it again and also fixed the auto completion for spider. (Will be enabled if the cards are in correct order on the tableau)

I gonna make a new release and hope it will be updated soon on f-droid too :)

Thanks again, and sorry for that stupid bug :D
